version: '3.8'

networks:
  app-network-public:
    driver: bridge

volumes:
  sql-server-data:
    driver: local
  sqldata:
  sqllog:
  sqlbackup:

services:
  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Passw0rd'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer'
      MSSQL_TCP_PORT: 1433
      MSSQL_INIT_DB: 'blog'
    ports:
      - '1433:1433'
    command: ["bash", "-c", "/opt/mssql/bin/sqlservr & sleep 20s && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Passw0rd -d master -Q 'CREATE DATABASE blog;' && tail -f /dev/null"]
